"""M4 mechanical mutant generator (deterministic, NO LLM).

Each operator is a pure string transform applied to a CORRECT solution's source.
Held-out mutants below are generated by applying an operator to the GOLD-patched
`structures.py` fix region (base="gold": apply gold.diff, then the transform).

TRAINING mutants are the four hand-authored M1 bads (bug_none/direct/first/dropown)
-- the failure modes the repair author anticipated. They live in m1_run.py.

The split criterion (explicit):
  * TRAINING  = human-anticipated failure modes; the battery the repair was
    validated against during M1. All are "MISSING marker" bugs.
  * HELD-OUT  = failure modes reached MECHANICALLY by the operator set, never
    consulted while designing the repair. Run only as the final gate. The
    duplication mutant (H_dup) is here on purpose: it is an EXTRA-marker failure
    mode that the training battery never contained -- the test of whether unseen
    mutants reveal a gap the human battery missed.
"""

OPERATORS = {
    "bool_flip":    "flip a boolean keyword-arg literal (False <-> True)",
    "mro_truncate": "restrict an __mro__ iteration to a slice",
    "cond_flip":    "negate an if-condition on the fix",
    "raise_drop":   "replace a `raise X` statement with `pass`",
    "noop_logic":   "replace the fix's key expression with pre-fix behavior",
}

# Held-out mutants: (operator, base solution, exact old -> new transform).
HELDOUT = {
    "H_dup": {
        "operator": "bool_flip", "base": "gold",
        "old": "get_unpacked_marks(obj, consider_mro=False)",
        "new": "get_unpacked_marks(obj, consider_mro=True)",
        "effect": "store_mark merges MRO marks at decoration -> markers DUPLICATED",
        "failure_mode": "EXTRA marker (duplication) -- absent from training set",
    },
    "H_onlyself": {
        "operator": "mro_truncate", "base": "gold",
        "old": "for x in obj.__mro__]",
        "new": "for x in obj.__mro__[:1]]",
        "effect": "collect only the class's own marks at read time",
        "failure_mode": "MISSING markers (a,b) -- overlaps training bug_direct",
    },
    "H_branchflip": {
        "operator": "cond_flip", "base": "gold",
        "old": "if not consider_mro:",
        "new": "if consider_mro:",
        "effect": "swap the direct-only vs MRO branches in get_unpacked_marks",
        "failure_mode": "MISSING markers at collection -- different mechanism",
    },
}

# raise_drop / noop_logic operators exist in the generator but have no anchor in
# this fix region (the two fixed functions contain no `raise`), so they are
# reported N/A for pytest-10356 rather than silently omitted.
NOT_APPLICABLE = {
    "raise_drop": "no `raise` in get_unpacked_marks/store_mark fix region",
}

TRAINING = ["bug_none", "bug_direct", "bug_first", "bug_dropown"]

if __name__ == "__main__":
    print("MECHANICAL MUTATION OPERATORS (deterministic, no LLM):")
    for k, v in OPERATORS.items():
        print(f"  {k:13s} {v}")
    print("\nTRAINING mutants (hand-authored M1 bads, all MISSING-marker):")
    for n in TRAINING:
        print(f"  {n}")
    print("\nHELD-OUT mutants (mechanically generated from gold; repair never saw them):")
    for name, m in HELDOUT.items():
        print(f"\n  {name}   [operator: {m['operator']}, base: {m['base']}]")
        print(f"    transform:  {m['old']}")
        print(f"           ->   {m['new']}")
        print(f"    effect:     {m['effect']}")
        print(f"    fail mode:  {m['failure_mode']}")
    print("\nOperators with no anchor in this fix region (reported, not hidden):")
    for k, v in NOT_APPLICABLE.items():
        print(f"  {k}: {v}")
